apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlserver-config
  namespace: microservices
data:
  ACCEPT_EULA: "Y"
  MSSQL_PID: "Express"
---
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secrets
  namespace: microservices
type: Opaque
data:
  # SA_PASSWORD: YourPassword123 (base64 encoded)
  SA_PASSWORD: WW91clBhc3N3b3JkMTIz
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlserver-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: ACCEPT_EULA
        - name: MSSQL_PID
          valueFrom:
            configMapKeyRef:
              name: sqlserver-config
              key: MSSQL_PID
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secrets
              key: SA_PASSWORD
        volumeMounts:
        - name: sqlserver-storage
          mountPath: /var/opt/mssql
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 1433
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: sqlserver-storage
        persistentVolumeClaim:
          claimName: sqlserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
  namespace: microservices
spec:
  selector:
    app: sqlserver
  ports:
  - port: 1433
    targetPort: 1433
  type: ClusterIP
